name: sync_to_gitee

on: [ push, delete, create ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: sync_to_gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_ACTIONS }}
        with:
          source-repo: git@github.com:kilcoder/kilcoder.git
          destination-repo: git@gitee.com:kilcoder/kilcoder.git
